title: "Yash Sharma"
email: yash37158@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
Hey foks ! Im yash sharma from India , currently pursuing my bachelors from Amity University , Mumbai.
Skill set include Front End Web Develeopment , Android Development and beginner in open souce contribution.
baseurl: "/" 
url: "https://yash37158@.github.io" 
twitter_username: yash37158
github_username:  yash37158

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
